spring:
  application:
    name: SpringBootCrudRepository
  datasource:
    password: Priyabrata
    url: jdbc:mysql://localhost:3306/sbms39
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
